"""Write a pins manifest into the files the DLL builds from (`rederive.py emit <manifest.json>`).

  src/pins.zig        every class, method and field under its stable name, plus the client
                      identity, Unity table offset, API code checks and readiness anchors
  src/pins.h          the same for the C probes, as PIN_<Class>_<member> macros
  src/dumper-rvas.zon the 194-entry API table

The modules reference these by stable name, so a client update regenerates three files instead of
hand-editing a dozen. Hex is written in lowercase without padding, exactly as the probes' header
strings always spelled it, so a regenerated file that carries the same values builds the same DLL
(the offline gate: every section but the PE timestamp and .buildid byte-identical).
"""
import json
import os

from rederive_runtime import write_zon

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, '..', '..', 'src'))


def ix(v):
    return int(v, 16) if isinstance(v, str) else v


def hooks(rt):
    """The identity the hook modules gate on: `hooks_identity` in a launch-1 manifest, else the client's."""
    return rt.get('hooks_identity') or rt


def zig_bytes(hexstr):
    b = bytes.fromhex(hexstr)
    return '[_]u8{ ' + ', '.join(f'0x{x:02X}' for x in b) + ' }'


def zig_string(hexstr):
    return '"' + ''.join(f'\\x{x:02x}' for x in bytes.fromhex(hexstr)) + '"'


def c_bytes(hexstr):
    return '{' + ','.join(f'0x{x:02X}' for x in bytes.fromhex(hexstr)) + '}'


def members(m):
    """{class: ([(member, method)], [(member, field)])} in manifest order."""
    out = {c: ([], []) for c in m['classes']}
    for stable, e in m['methods'].items():
        c, member = stable.split('.', 1)
        out.setdefault(c, ([], []))[0].append((member, e))
    for stable, e in m['fields'].items():
        c, member = stable.split('.', 1)
        out.setdefault(c, ([], []))[1].append((member, e))
    return out


def emit_zig(m):
    rt = m['runtime']
    lines = [f'//! GENERATED by tools/update/rederive.py emit from tools/update/pins/{m["version"]}.json.',
             '//! Do not edit: re-derive the manifest and emit again (docs/client-update-playbook.md).', '',
             'pub const Method = struct { name: []const u8, params: usize, rva: usize };',
             'pub const Field = struct { name: []const u8, offset: usize };', '',
             f'pub const client = "{m["version"]}";',
             '/// The client the hook modules accept. Differs from dumper_size_of_image only in a',
             '/// launch-1 build (`rederive.py prepare`): there the hooks keep the OLD identity so they',
             '/// refuse deterministically while the dumper runs against the new client.',
             f'pub const timestamp: u32 = 0x{ix(hooks(rt)["timestamp"]):X};',
             f'pub const size_of_image: u32 = 0x{ix(hooks(rt)["size_of_image"]):X};',
             f'pub const dumper_size_of_image: u32 = 0x{ix(rt["size_of_image"]):X};',
             f'pub const unity_table_offset: usize = 0x{ix(rt["unity_table_offset"]):x};',
             'pub const api_checks = .{']
    for slot, b in rt['api_checks'].items():
        lines.append(f'    .{{ {slot}, {zig_string(b)} }},')
    lines += ['};', f'pub const main_thread_rva: usize = 0x{ix(rt["readiness"]["main_thread_rva"]):x};',
              'pub const readiness_anchors = .{']
    for rva, b in rt['readiness']['anchors']:
        lines.append(f'    .{{ 0x{ix(rva):x}, {zig_string(b)} }},')
    lines.append('};')
    for c, (meths, fields) in members(m).items():
        cls = m['classes'].get(c) or {}
        lines += ['', f'pub const {c} = struct {{', f'    pub const class_name = "{cls.get("name") or ""}";']
        for member, e in meths:
            if not e.get('rva'):
                continue
            lines.append(f'    pub const {member} = Method{{ .name = "{e["name"]}", .params = {e["params"]}, .rva = 0x{ix(e["rva"]):X} }};')
            # the bare RVA too: reading .rva off the struct lays its name string out early
            lines.append(f'    pub const {member}_rva: usize = 0x{ix(e["rva"]):X};')
            if e.get('prologue'):
                lines.append(f'    pub const {member}_prologue = {zig_bytes(e["prologue"])};')
        for member, e in fields:
            if e.get('offset') is None:
                continue
            lines.append(f'    pub const {member} = Field{{ .name = "{e.get("name") or ""}", .offset = 0x{ix(e["offset"]):x} }};')
        lines.append('};')
    return '\n'.join(lines) + '\n'


def emit_c(m):
    rt = m['runtime']
    lines = [f'/* GENERATED by tools/update/rederive.py emit from tools/update/pins/{m["version"]}.json.',
             ' * Do not edit: re-derive the manifest and emit again. Hex is lowercase and unpadded so the',
             ' * probes can splice these into their header strings unchanged. */',
             '#ifndef THAUMIEL_PINS_H', '#define THAUMIEL_PINS_H',
             '#define PIN_STR_(x) #x', '#define PIN_STR(x) PIN_STR_(x)',
             f'#define PIN_CLIENT "{m["version"]}"',
             f'#define PIN_VERSION "{m["version"].replace("CNBetaWin", "")}"',
             f'#define PIN_TIMESTAMP 0x{ix(hooks(rt)["timestamp"]):x}',
             f'#define PIN_SIZE_OF_IMAGE 0x{ix(hooks(rt)["size_of_image"]):x}']
    for c, (meths, fields) in members(m).items():
        cls = m['classes'].get(c) or {}
        if cls.get('name'):
            lines.append(f'#define PIN_{c}_CLASS "{cls["name"]}"')
        for member, e in meths:
            if not e.get('rva'):
                continue
            lines.append(f'#define PIN_{c}_{member}_RVA 0x{ix(e["rva"]):x}')
            lines.append(f'#define PIN_{c}_{member}_METHOD "{e["name"]}"')
            if e.get('fingerprint'):
                lines.append(f'#define PIN_{c}_{member}_FINGERPRINT {c_bytes(e["fingerprint"])}')
        for member, e in fields:
            if e.get('offset') is not None:
                lines.append(f'#define PIN_{c}_{member} 0x{ix(e["offset"]):x}')
    for stable, s in m.get('sets', {}).items():
        c, member = stable.split('.', 1)
        lines.append(f'#define PIN_{c}_{member} {{' + ','.join(x for x in s['value']) + '}')
        lines.append(f'#define PIN_{c}_{member}_TEXT "' + ','.join(x for x in s['value']) + '"')
        for i, x in enumerate(s['value']):  # elements, and without 0x for TSV column names
            lines.append(f'#define PIN_{c}_{member}_{i} {x}')
            lines.append(f'#define PIN_{c}_{member}_{i}_X "{x[2:]}"')
    for stable, s in m.get('sizes', {}).items():
        c, member = stable.split('.', 1)
        lines.append(f'#define PIN_{c}_{member} {s["value"]}')
    lines.append('#endif')
    return '\n'.join(lines) + '\n'


def emit(manifest_path, src=SRC):
    m = json.load(open(manifest_path))
    missing = [k for k in ('runtime',) if k not in m]
    if missing:
        raise SystemExit(f'{manifest_path}: no {missing} section (run bootstrap/table first)')
    written = []
    for name, text in (('pins.zig', emit_zig(m)), ('pins.h', emit_c(m)),
                       ('dumper-rvas.zon', write_zon([ix(x) for x in m['runtime']['api_table']]))):
        path = os.path.join(src, name)
        with open(path, 'w', newline='\n') as f:
            f.write(text)
        written.append(path)
    return written


# --- the readers: tools/per-hit-log.mjs LAYOUTS and sheet-webapp tools/client-build-constants.mjs -----
LAYOUT_KEYS = ['attacker_entity', 'target_entity', 'damage', 'crit', 'hit_split', 'dmg_mv', 'daze_mv', 'energy',
               'decibels', 'daze', 'daze_requested', 'buildup_requested', 'buildup_applied', 'atk', 'impact',
               'anomaly_mastery', 'anomaly_proficiency', 'level', 'target_state', 'dmg_mult', 'f11c', 'f174', 'f0f8',
               'display_skill_id']
# damage_result.c names its six string columns by 3.3.0's offsets, whatever the build's offsets are
STRING_COLUMNS = ['s10', 's40', 's58', 's70', 'sa0', 'sc0']


def layout_values(m, previous=None):
    """-> (values dict, pending notes). Capture-measured values the manifest lacks are carried from
    `previous` and named in the notes, never filled silently."""
    f = m['fields']
    off = lambda k: ix((f.get(k) or {}).get('offset'))  # noqa: E731
    vals = {k: off('DamageResult.' + k) for k in LAYOUT_KEYS}
    vals['target_state_int'] = True
    pending = [k for k in LAYOUT_KEYS if vals[k] is None]
    strings = [ix(x) for x in m['sets']['DamageResult.strings']['value']]
    attn = off('DamageResult.attenuation_curve')
    vals['attn_col'] = STRING_COLUMNS[strings.index(attn)] if attn in strings else None
    vals['snapshot_atk'] = off('AttackSnapshot.atk')
    roles = ((m.get('measured') or {}).get('HitNames.roles') or {}).get('value')
    if roles is None and previous:
        roles = previous['measured']['HitNames.roles']['value']
        pending.append(f'a8 (carried from {previous["version"]})')
    vals['a8'] = roles
    return vals, pending


def layout_entry(m, previous=None):
    vals, pending = layout_values(m, previous)
    js = lambda v: 'null' if v is None else ('true' if v is True else (f'"{v}"' if isinstance(v, str) else hex(v)))  # noqa: E731
    head = ', '.join(f'{k}: {js(vals[k])}' for k in LAYOUT_KEYS)
    a8 = vals['a8']
    tail = (f'target_state_int: true, attn_col: {js(vals["attn_col"])}, snapshot_atk: {js(vals["snapshot_atk"])}, '
            f'a8: {{ ability: {a8["ability"]}, attack_property: {a8["attack_property"]}, other: {a8["other"]} }}' if a8 else
            f'target_state_int: true, attn_col: {js(vals["attn_col"])}, snapshot_atk: {js(vals["snapshot_atk"])}, a8: null')
    note = (f'  // {m["version"]}: generated by tools/update/rederive.py from tools/update/pins/{m["version"]}.json.'
            + (f' PENDING the first capture (measure): {", ".join(pending)}.' if pending else ''))
    return f'{note}\n  "{m["version"]}": {{ {head},\n    {tail} }},\n', pending


def build_constants_entry(m):
    rs = m['return_sites'].get('AnimHit.caller_return') or {}
    c = m['classes']
    return (f"  '{m['version']}': {{ animFrame: '0x{ix(rs.get('address') or '0x0'):X}', "
            f"audioEffectClass: '{(c.get('AudioEffectEvent') or {}).get('name')}', "
            f"animEventHandlerClass: '{(c.get('AnimEventHandlerEvent') or {}).get('name')}' }},\n")


def insert_layout(path, m, previous=None):
    """Add the entry before the `};` closing LAYOUTS. Never replaces an existing entry."""
    with open(path, encoding='utf-8', newline='') as f:
        text = f.read()  # untranslated: the file's own line endings (CRLF) are kept byte for byte
    if f'"{m["version"]}":' in text:
        return False, 'entry exists; not replaced'
    eol = '\r\n' if '\r\n' in text else '\n'
    start = text.index('const LAYOUTS = {')
    close = text.index(eol + '};', start) + len(eol)
    entry, pending = layout_entry(m, previous)
    with open(path, 'w', encoding='utf-8', newline='') as f:
        f.write(text[:close] + entry.replace('\n', eol) + text[close:])
    return True, pending
