// In-game names for the readable combat log, from skill-display-names.json (generated by
// sheet-webapp's tools/export-skill-display-names.mjs; names only). Pure helpers, so
// readable-log.mjs stays a thin CLI and these can be tested (test-display-names.mjs).
import fs from "node:fs";

const TABLE = new URL("./skill-display-names.json", import.meta.url);

/** The name table, or null when this install has none (then the log keeps client names). */
export function loadDisplayNames(file = TABLE) {
  return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, "utf8")) : null;
}

/** entity -> name: the Agent most of the entity's identified hits belong to; else `fallback(entity)`.
 * A Bangboo whose codename is not in codenames.json ("Bangboo_Ultraboo") is named by its skills. */
export function entityNames(rows, names, fallback) {
  const votes = new Map();
  for (const r of rows) {
    const agent = names?.skills?.[r.skill_id]?.[0];
    if (!agent) continue;
    const v = votes.get(r.attacker_entity) ?? new Map();
    v.set(agent, (v.get(agent) ?? 0) + 1);
    votes.set(r.attacker_entity, v);
  }
  const out = new Map();
  for (const r of rows) {
    if (out.has(r.attacker_entity)) continue;
    const v = votes.get(r.attacker_entity);
    out.set(r.attacker_entity, v ? [...v].sort((a, b) => b[1] - a[1])[0][0] : fallback(r.attacker_entity));
  }
  return out;
}

const CORE_PASSIVE = /^#?(.+?)_UniqueSkill(_|$)/;
/** The in-game action for a row, or null when the table does not know it. A Core Passive hit
 * (`<Codename>_UniqueSkill...`) has no skill id; it is labelled with its owner's Core Passive, named
 * with the owner when the game credits another Agent (Sunna's Cat's Gaze burst lands as the
 * triggering Agent's hit). */
export function actionName(r, attacker, names) {
  if (!names) return null;
  const known = names.skills?.[r.skill_id];
  if (known) return known[1];
  const code = CORE_PASSIVE.exec(r.ability_name || "")?.[1];
  if (!code) return null;
  const owner = names.codenames?.[code.toLowerCase()] ?? attacker;
  const core = names.corePassive?.[owner] ?? "Core Passive";
  return owner === attacker ? core : `${owner}'s ${core}`;
}

/** A summon's hit is logged twice: once by the summon entity with 0 damage and once by its Agent's
 * entity with the damage. Per Agent name, the entity with the most damage is the Agent's; a
 * zero-damage row from another entity of the same name is dropped when the Agent's entity has the
 * same attack on the same target within 20 ms and any resource on the copy matches. One-to-one.
 * (Same rule as sheet-webapp's run export, removeSummonDuplicates.) */
export function dropSummonCopies(rows, nameOf) {
  const damage = new Map();
  for (const r of rows) {
    const per = damage.get(nameOf(r.attacker_entity)) ?? new Map();
    per.set(r.attacker_entity, (per.get(r.attacker_entity) ?? 0) + (+r.damage_unrounded || 0));
    damage.set(nameOf(r.attacker_entity), per);
  }
  const owner = new Map([...damage].map(([name, per]) => [name, [...per].sort((a, b) => b[1] - a[1])[0]]));
  const used = new Set(), drop = new Set();
  const same = (a, b, k) => !(+a[k]) || +a[k] === +b[k];
  for (const r of rows) {
    const name = nameOf(r.attacker_entity), o = owner.get(name);
    if (!o || o[1] <= 0 || o[0] === r.attacker_entity || +r.damage_unrounded !== 0) continue;
    const match = rows.find((s) => !used.has(s) && s.attacker_entity === o[0] && s.target_entity === r.target_entity && s.skill_id === r.skill_id
      && s.attack_property_name === r.attack_property_name && Math.abs(+s.elapsed_ms - +r.elapsed_ms) <= 20
      && ["daze", "buildup_applied", "energy", "decibels"].every((k) => same(r, s, k)));
    if (match) { used.add(match); drop.add(r); }
  }
  return rows.filter((r) => !drop.has(r));
}
