//! GENERATED by tools/update/rederive.py emit from tools/update/pins/CNBetaWin3.3.4.json.
//! Do not edit: re-derive the manifest and emit again (docs/client-update-playbook.md).

pub const Method = struct { name: []const u8, params: usize, rva: usize };
pub const Field = struct { name: []const u8, offset: usize };

pub const client = "CNBetaWin3.3.4";
/// The client the hook modules accept. Differs from dumper_size_of_image only in a
/// launch-1 build (`rederive.py prepare`): there the hooks keep the OLD identity so they
/// refuse deterministically while the dumper runs against the new client.
pub const timestamp: u32 = 0x6AB435F6;
pub const size_of_image: u32 = 0x21714000;
pub const dumper_size_of_image: u32 = 0x21714000;
pub const unity_table_offset: usize = 0x1f9b6c8;
pub const api_checks = .{
    .{ 63, "\x48\x83\xec\x28\x48\x8b\x05" },
    .{ 65, "\x48\x8b\x0d\x89\x54\xdb\x04" },
    .{ 73, "\x48\xb8\xbe\x70\x37\x76\x11\x6e\x5a\x5e" },
    .{ 75, "\x8b\x41\x1c\x25\xff\xff\xff\x00" },
    .{ 115, "\x48\x8b\x51\x38\x48\x85\xd2" },
    .{ 152, "\xe9\x6b\x76\x08\x00" },
    .{ 167, "\xb8\x7e\x66\x04\x94\x03\x41\x3c" },
};
pub const main_thread_rva: usize = 0x56dcbc0;
pub const readiness_anchors = .{
    .{ 0x98442c, "\xe8\x2f\xb0\x02\x00\x48\x89\x05\x88\x87\xd5\x04" },
    .{ 0x987180, "\x48\x89\xc6\x48\x8b\x8d\x80\x02\x00\x00\x8b\x41\x20\x89\x46\x10\xc7\x46\x14\x00\x00\x00\x00\x48\x89\x71\x10" },
    .{ 0x9871b8, "\x48\x8b\x7f\x10" },
    .{ 0x9871d6, "\x48\x89\x77\x70" },
};

pub const PropertyTable = struct {
    pub const class_name = "IHNAJAGFLDC";
    pub const set = Method{ .name = "GOPFMPMAFMG", .params = 4, .rva = 0x18D640A0 };
    pub const set_rva: usize = 0x18D640A0;
    pub const set_prologue = [_]u8{ 0x41, 0x56, 0x56, 0x57, 0x53, 0x48, 0x81, 0xEC, 0x88, 0x00, 0x00, 0x00 };
    pub const get = Method{ .name = "GEHFLAPAAJJ", .params = 3, .rva = 0x18D5E840 };
    pub const get_rva: usize = 0x18D5E840;
    pub const get_prologue = [_]u8{ 0x41, 0x56, 0x56, 0x57, 0x53, 0x48, 0x83, 0xEC, 0x28, 0x4C, 0x89, 0xCB };
    pub const get_double = Method{ .name = "OHEECDKONIF", .params = 2, .rva = 0x18D63E60 };
    pub const get_double_rva: usize = 0x18D63E60;
    pub const get_double_prologue = [_]u8{ 0x56, 0x57, 0x53, 0x48, 0x83, 0xEC, 0x70, 0x66, 0x0F, 0x29, 0x74, 0x24 };
};

pub const PropertyNotifier = struct {
    pub const class_name = "JEKJGCLPBMC";
    pub const notify = Method{ .name = "HCNJJOANJKM", .params = 3, .rva = 0x19DB2600 };
    pub const notify_rva: usize = 0x19DB2600;
    pub const notify_prologue = [_]u8{ 0x41, 0x57, 0x41, 0x56, 0x41, 0x55, 0x41, 0x54, 0x56, 0x57, 0x55, 0x53 };
};

pub const ModifierInstance = struct {
    pub const class_name = "JIBFNGPOOJJ";
    pub const init = Method{ .name = "LHJAJGDKANN", .params = 4, .rva = 0x14F6EB30 };
    pub const init_rva: usize = 0x14F6EB30;
    pub const init_prologue = [_]u8{ 0x55, 0x41, 0x57, 0x41, 0x56, 0x41, 0x55, 0x41, 0x54, 0x56, 0x57, 0x53, 0x48, 0x81, 0xEC, 0x08, 0x01, 0x00, 0x00 };
    pub const attach = Method{ .name = "CIBFJCNMMFB", .params = 0, .rva = 0x14F70230 };
    pub const attach_rva: usize = 0x14F70230;
    pub const attach_prologue = [_]u8{ 0x56, 0x57, 0x53, 0x48, 0x83, 0xEC, 0x20, 0x48, 0x89, 0xCE };
    pub const detach = Method{ .name = "MEGHDEFMFHB", .params = 0, .rva = 0x14F6D980 };
    pub const detach_rva: usize = 0x14F6D980;
    pub const detach_prologue = [_]u8{ 0x56, 0x48, 0x83, 0xEC, 0x20, 0x48, 0x89, 0xCE };
    pub const to_string = Method{ .name = "ToString", .params = 0, .rva = 0x14F6B2E0 };
    pub const to_string_rva: usize = 0x14F6B2E0;
    pub const owner = Field{ .name = "EPEJLGDHNCG", .offset = 0x1d8 };
    pub const caster = Field{ .name = "NNDHBCEMAJG", .offset = 0x200 };
    pub const ability = Field{ .name = "IACOBBCEMNN", .offset = 0x1e0 };
    pub const config = Field{ .name = "LLGALKCBMIM", .offset = 0x1f0 };
    pub const flags = Field{ .name = "DONJJPGJDKH", .offset = 0x218 };
    pub const slot = Field{ .name = "KFNOBOMPNLK", .offset = 0x21c };
    pub const stacks = Field{ .name = "EEPIMNKHLMP", .offset = 0x224 };
};

pub const ModifierConfig = struct {
    pub const class_name = "DMJBGLLLJOI";
    pub const parse_binary = Method{ .name = "AICDOJFCANO", .params = 2, .rva = 0x19328070 };
    pub const parse_binary_rva: usize = 0x19328070;
    pub const stacking_getter = Method{ .name = "DNKNIJMPMJI", .params = 0, .rva = 0x193BCC90 };
    pub const stacking_getter_rva: usize = 0x193BCC90;
    pub const name = Field{ .name = "ICPOJFEGKHK", .offset = 0x4d8 };
    pub const stacking = Field{ .name = "DCIFPGNNBNO", .offset = 0x988 };
    pub const duration = Field{ .name = "OIOBBLGOIGC", .offset = 0x998 };
    pub const max_stacks = Field{ .name = "LMIHDAMJFIM", .offset = 0x994 };
};

pub const StunMixin = struct {
    pub const class_name = "FLDOPGOJDOP";
    pub const enter = Method{ .name = "KIKJBCJPEMN", .params = 0, .rva = 0x15F876B0 };
    pub const enter_rva: usize = 0x15F876B0;
    pub const enter_prologue = [_]u8{ 0x41, 0x57, 0x41, 0x56, 0x41, 0x54, 0x56, 0x57, 0x53, 0x48, 0x83, 0xEC, 0x38 };
    pub const update = Method{ .name = "LFKBMOMEFEL", .params = 1, .rva = 0x15F81460 };
    pub const update_rva: usize = 0x15F81460;
    pub const update_prologue = [_]u8{ 0x56, 0x48, 0x83, 0xEC, 0x60, 0x44, 0x0F, 0x29, 0x44, 0x24, 0x50, 0x0F, 0x29, 0x7C, 0x24, 0x40 };
    pub const be_hit = Method{ .name = "LILNHAPOBDH", .params = 1, .rva = 0x15F83660 };
    pub const be_hit_rva: usize = 0x15F83660;
    pub const fields_witness = Method{ .name = "GLBMKIMBLMD", .params = 0, .rva = 0x15F7EA80 };
    pub const fields_witness_rva: usize = 0x15F7EA80;
    pub const entity = Field{ .name = "DNJPIGGHPJP", .offset = 0x58 };
    pub const cur_at_entry = Field{ .name = "MDOAGNPPGCJ", .offset = 0xb4 };
    pub const entered = Field{ .name = "KMGNMAGIAJL", .offset = 0xf7 };
    pub const stunned = Field{ .name = "KBNPGMEDNCC", .offset = 0xc4 };
    pub const config_value = Field{ .name = "DNLJDMJAHIB", .offset = 0xc0 };
    pub const cur_stun = Field{ .name = "OKPGKCIPPOL", .offset = 0xe8 };
    pub const remaining = Field{ .name = "JFMAOEHJGKM", .offset = 0xb8 };
    pub const daze_target = Field{ .name = "MHGOJBKIBBB", .offset = 0xf0 };
};

pub const EntityWrapper = struct {
    pub const class_name = "CAJPNCGFJEG";
};

pub const TimeScaleManager = struct {
    pub const class_name = "FEIGLFFGABJ";
    pub const update = Method{ .name = "Update", .params = 1, .rva = 0x1942A6A0 };
    pub const update_rva: usize = 0x1942A6A0;
    pub const update_prologue = [_]u8{ 0x56, 0x57, 0x53, 0x48, 0x83, 0xEC, 0x50, 0x0F, 0x29, 0x7C, 0x24, 0x40 };
    pub const frame = Field{ .name = "MGDAMOEKKHB", .offset = 0xb4 };
    pub const raw = Field{ .name = "CEBCLBBMGPL", .offset = 0x78 };
    pub const mult = Field{ .name = "<ECBKLOMGKAH>k__BackingField", .offset = 0xe0 };
    pub const pause = Field{ .name = "DOPCCDPPNLN", .offset = 0xb0 };
    pub const world = Field{ .name = "FLNNELBLDNL", .offset = 0xd0 };
    pub const unscaled = Field{ .name = "JHBFGEGDKCN", .offset = 0x95 };
    pub const scaled_dt = Field{ .name = "NJBFIEIIMIK", .offset = 0xf8 };
};

pub const AnimEventSystem = struct {
    pub const class_name = "ODOHDPHKFIC";
    pub const drain = Method{ .name = "POGFGHIFDFJ", .params = 1, .rva = 0x13C42F30 };
    pub const drain_rva: usize = 0x13C42F30;
    pub const drain_prologue = [_]u8{ 0x55, 0x41, 0x57, 0x41, 0x56, 0x56, 0x57, 0x53, 0x48, 0x81, 0xEC, 0xA8, 0x00, 0x00, 0x00 };
};

pub const AnimEventComponent = struct {
    pub const class_name = "";
    pub const owner = Field{ .name = "", .offset = 0x38 };
    pub const queue = Field{ .name = "", .offset = 0x50 };
};

pub const DamageTextController = struct {
    pub const class_name = "UIInLevelDamageTextContainerChildWindowController";
    pub const query = Method{ .name = "OLELPLKJFNF", .params = 16, .rva = 0x14AE0070 };
    pub const query_rva: usize = 0x14AE0070;
};

pub const ResultConverter = struct {
    pub const class_name = "OLIFMMEBMGL";
    pub const convert = Method{ .name = "LHDFOBIAEGA", .params = 6, .rva = 0x19BF3530 };
    pub const convert_rva: usize = 0x19BF3530;
};

pub const ResultFactory = struct {
    pub const class_name = "ONBKKHGOGDE";
    pub const create = Method{ .name = "NDPEJBBAFPC", .params = 7, .rva = 0x1BFC5500 };
    pub const create_rva: usize = 0x1BFC5500;
    pub const energy_copy = Method{ .name = "FNLPDHIDGNM", .params = 2, .rva = 0x1BFC7110 };
    pub const energy_copy_rva: usize = 0x1BFC7110;
};

pub const DamageResult = struct {
    pub const class_name = "HAJJIAGHAFN";
    pub const energy_reset = Method{ .name = "KGGFEPIELMH", .params = 0, .rva = 0x17109800 };
    pub const energy_reset_rva: usize = 0x17109800;
    pub const attacker_entity = Field{ .name = "KANBDNALFKB", .offset = 0x68 };
    pub const target_entity = Field{ .name = "FIAPCAHGJJE", .offset = 0x20 };
    pub const damage = Field{ .name = "<DGNAFAMKLAO>k__BackingField", .offset = 0x118 };
    pub const crit = Field{ .name = "GBCJJMDOODB", .offset = 0x19c };
    pub const hit_split = Field{ .name = "BHCKCNONJCJ", .offset = 0x184 };
    pub const dmg_mv = Field{ .name = "IAIFDHEOOAM", .offset = 0xf0 };
    pub const daze_mv = Field{ .name = "HDDIJPMNCLJ", .offset = 0x278 };
    pub const energy = Field{ .name = "JGIBLJAKFBK", .offset = 0x188 };
    pub const decibels = Field{ .name = "CMPPNKLMMOG", .offset = 0x168 };
    pub const daze = Field{ .name = "BCDIDINEPFK", .offset = 0x240 };
    pub const daze_requested = Field{ .name = "KNAMPGGEDGO", .offset = 0x17c };
    pub const buildup_requested = Field{ .name = "INGNIHBGMBJ", .offset = 0x1f0 };
    pub const buildup_applied = Field{ .name = "EEEKMGKGLKK", .offset = 0x174 };
    pub const atk = Field{ .name = "ALKPIIHNLOF", .offset = 0x110 };
    pub const impact = Field{ .name = "IHIMDBBOJHN", .offset = 0x134 };
    pub const anomaly_mastery = Field{ .name = "PPLAMNFKGAG", .offset = 0x258 };
    pub const anomaly_proficiency = Field{ .name = "ECDEMFNOONE", .offset = 0x21c };
    pub const level = Field{ .name = "BCGOBDCINDG", .offset = 0x190 };
    pub const dmg_mult = Field{ .name = "KJBMBBLEKGL", .offset = 0x1fc };
    pub const f11c = Field{ .name = "NPKEGJGAOEC", .offset = 0x200 };
    pub const f174 = Field{ .name = "ONIONHAIDMC", .offset = 0x1b0 };
    pub const f0f8 = Field{ .name = "MAOHECCANID", .offset = 0x1bc };
    pub const display_skill_id = Field{ .name = "IPLBCANCAMN", .offset = 0x208 };
    pub const attenuation_curve = Field{ .name = "EPFGCDLAKOF", .offset = 0x88 };
    pub const geometry = Field{ .name = "<EEIBNGFCMLE>k__BackingField", .offset = 0x60 };
    pub const stat_dict = Field{ .name = "DNEBJEPOKIL", .offset = 0xb0 };
    pub const hit_names = Field{ .name = "HEONIJOOEIL", .offset = 0x80 };
    pub const attack_tags = Field{ .name = "IBODEHKOMOD", .offset = 0x48 };
    pub const float_list = Field{ .name = "FFHKOLGEDCH", .offset = 0xc8 };
    pub const team_props = Field{ .name = "KOGNGKMMENA", .offset = 0xd0 };
    pub const base_props = Field{ .name = "KMMFALDDJFJ", .offset = 0xe0 };
};

pub const AnomalyGauge = struct {
    pub const class_name = "HEECCHMMMHJ";
    pub const be_hit = Method{ .name = "PLILBLPMLGE", .params = 1, .rva = 0x167E0190 };
    pub const be_hit_rva: usize = 0x167E0190;
    pub const max_update = Method{ .name = "BNEIHEHMKDF", .params = 0, .rva = 0x167DE730 };
    pub const max_update_rva: usize = 0x167DE730;
    pub const entity = Field{ .name = "<FJKPINMGBDK>k__BackingField", .offset = 0x58 };
    pub const cur = Field{ .name = "IGONGHEOMPF", .offset = 0x6c };
    pub const f68 = Field{ .name = "OHNHMKEDCIP", .offset = 0x84 };
    pub const element = Field{ .name = "FPDAKLNCLAA", .offset = 0x78 };
    pub const variant = Field{ .name = "FIEBGKJJPAN", .offset = 0x70 };
    pub const variant2 = Field{ .name = "LFIEOBBJDKC", .offset = 0x88 };
    pub const max = Field{ .name = "<MDJANMMBCBI>k__BackingField", .offset = 0x74 };
};

pub const AnomalyHitEvent = struct {
    pub const class_name = "";
    pub const ctx = Field{ .name = "", .offset = 0x20 };
};

pub const HitNames = struct {
    pub const class_name = "HMKMLBCLJAH";
};

pub const HitContext = struct {
    pub const class_name = "";
    pub const result = Field{ .name = "", .offset = 0x30 };
};

pub const AttackSnapshot = struct {
    pub const class_name = "";
    pub const atk = Field{ .name = "", .offset = 0x188 };
    pub const daze_mv = Field{ .name = "", .offset = 0x1a4 };
};

pub const AudioEffectEvent = struct {
    pub const class_name = "HMHFPKAALAP";
};

pub const AnimEventHandlerEvent = struct {
    pub const class_name = "PCJHIABICAM";
};
